name: Demonstração de Variáveis de Ambiente

on:
  push: 
    branches: [main]
  workflow_dispatch:
    
#Variaveis de ambiente no nivel de workflow
env:
  WORKFLOW_VAR: "Variável definida no nivel do workflow"
  AMBIENTE: "producao"

jobs:
  demonstracao-variaveis:
    runs-on: ubuntu-latest
    
    #variaveis de ambiente nivel job
    env:
      JOB_VAR: "Variavel definida no nivel do job"
      USUARIO: "devops-user"
      VERSAO_APP: "1.0.0"

    steps:
      - name: Exibir variáveis do workflow
        run: |
          echo "=== Variaveis do workflow ==="
          echo "Variável WORKFLOW_VAR: ${{ env.WORKFLOW_VAR }}"
          echo "Ambiente: ${{ env.AMBIENTE }}"
          echo "Versão da aplicação: ${{ env.VERSAO_APP }}"

      - name: Exibir variáveis do job
        run: |
          echo "=== Variáveis do Job ==="
          echo "Variavel JOB_VAR: ${{ env.JOB_VAR }}"
          echo "Usuário: ${{ env.USUARIO }}"

      - name: Exibir variavel do step
        env:
          STEP_VAR: "Variavel definida no nivel step"
          MENSAGEM: "Este é um exemplo prático"
        run: |
          echo "=== Variaveis do step ==="
          echo "Variavel STEP_VAR: ${{ env.STEP_VAR }}"
          echo "Mensagem: ${{ env.MENSAGEM }}"

      - name: Combinar variaveis
        env: 
          STEP_ESPECIFICO: "step-value"
        run: |
          echo "=== Combinacao de variaveis ==="
          echo "workflow: ${{ env.WORKFLOW_VAR }}"
          echo "Job: ${{ env.JOB_VAR }}"
          echo "Ambiente de deploy: ${{ env.AMBIENTE }} "
          echo "Step: ${{ env.STEP_ESPECIFICO }}"
          echo "Todas acessiveis no mesmo contexto"

      - name: Usar variaveis em comandos práticos
        env:
          NOME_PROJETO: "lab-variaveis"
          TIMESTAMP: "2025-01-13"
        run: |
         echo "=== Exemplo pratico ==="
         echo "Compilando projeto: ${{ env.NOME_PROJETO }}"
         echo "Data do build: ${{ env.TIMESTAMP }}"
         echo "Ambiente de deploy: ${{ env.AMBIENTE }}"
         echo "Versão: ${{ env.VERSAO_APP }}"